export const configRouter = {
  home: "/",
  login: "/login",
  signUp: "/signup",
  forgetPassword: "/forget-password",
  resetPassword: "/reset-password",
  optConfirm: "/otp-signup",
  // customer router
  store: "/store",
  productDetail: "/product/:id",
  searchProduct: "/search",
  profile: "/profile",
  dashboard: "/dashboard",
  changePassword: "/change-password",
  myOrder: "/my-order",
  defaultAddress: "/default-address",
  coupon: "/coupon",
  checkout: "/checkout",
  thanks: "/thanks/:id",
};
